# Generated by Django 4.2.7 on 2023-12-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="20%y/%m/%d"),
                ),
                ("abbreviation", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Fuel_Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Karat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Gold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy_price", models.FloatField(blank=True, null=True)),
                ("sell_price", models.FloatField(blank=True, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_currency",
                        to="exchange_rates.currency",
                    ),
                ),
                (
                    "karat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold",
                        to="exchange_rates.karat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fuel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_currency",
                        to="exchange_rates.currency",
                    ),
                ),
                (
                    "fuel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_types",
                        to="exchange_rates.karat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Currency_Prices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy_market_price", models.FloatField(blank=True, null=True)),
                ("sell_market_price", models.FloatField(blank=True, null=True)),
                ("buy_bank_price", models.FloatField(blank=True, null=True)),
                ("sell_bank_price", models.FloatField(blank=True, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_currency_prices",
                        to="exchange_rates.currency",
                    ),
                ),
            ],
        ),
    ]
