# Generated by Django 4.2.7 on 2023-12-07 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0019_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency_prices",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 8, 1, 34, 36, 326182)
            ),
        ),
        migrations.AlterField(
            model_name="fuel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 8, 1, 34, 36, 330181)
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 8, 1, 34, 36, 328182)
            ),
        ),
    ]
