# Generated by Django 4.2.7 on 2023-12-09 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0029_alter_currency_prices_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency_prices",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 9, 3, 55, 36, 214935)
            ),
        ),
        migrations.AlterField(
            model_name="fuel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 9, 3, 55, 36, 218933)
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 9, 3, 55, 36, 216935)
            ),
        ),
    ]
