# Generated by Django 4.2.7 on 2023-12-24 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0043_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gold_types",
            name="name_ar",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="fuel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 24, 5, 13, 58, 123725)
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 24, 5, 13, 58, 122726)
            ),
        ),
    ]
