# Generated by Django 4.2.7 on 2023-12-24 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0044_gold_types_name_ar_alter_fuel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 24, 5, 37, 5, 994758)
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 24, 5, 37, 5, 992758)
            ),
        ),
    ]
