# Generated by Django 4.2.7 on 2023-12-25 04:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0045_alter_fuel_created_at_alter_gold_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 25, 6, 34, 59, 303855)
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 25, 6, 34, 59, 301855)
            ),
        ),
        migrations.CreateModel(
            name="Foreign_Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_foreign",
                        to="exchange_rates.currency",
                    ),
                ),
                (
                    "exchange_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_exchange_foreign",
                        to="exchange_rates.currency",
                    ),
                ),
            ],
        ),
    ]
