# Generated by Django 4.2.7 on 2023-12-28 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0058_post_image_alter_fuel_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField()),
                ("about_ar", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 28, 6, 14, 18, 33256)
                    ),
                ),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "About",
            },
        ),
        migrations.CreateModel(
            name="Privacy_Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("privacy_policy", models.TextField()),
                ("privacy_policy_ar", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 28, 6, 14, 18, 34256)
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy_Policy",
                "verbose_name_plural": "Privacy_Policy",
            },
        ),
        migrations.CreateModel(
            name="Terms_Conditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terms_conditions", models.TextField()),
                ("terms_conditions_ar", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 28, 6, 14, 18, 34256)
                    ),
                ),
            ],
            options={
                "verbose_name": "Terms_Conditions",
                "verbose_name_plural": "Terms_Conditions",
            },
        ),
        migrations.AlterField(
            model_name="fuel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 28, 6, 14, 18, 31253)
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 28, 6, 14, 18, 29255)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 28, 6, 14, 18, 32258)
            ),
        ),
    ]
