# Generated by Django 4.2.7 on 2024-01-16 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exchange_rates",
            "0060_links_alter_about_created_at_alter_fuel_created_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("keywords", models.TextField()),
                ("description_ar", models.TextField()),
                ("keywords_ar", models.TextField()),
            ],
            options={
                "verbose_name": "meta details",
                "verbose_name_plural": "meta details",
            },
        ),
        migrations.AlterModelOptions(
            name="links",
            options={"verbose_name": "links", "verbose_name_plural": "links"},
        ),
        migrations.AlterField(
            model_name="about",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 23, 19, 38, 546450)
            ),
        ),
        migrations.AlterField(
            model_name="fuel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 23, 19, 38, 546450)
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 23, 19, 38, 546450)
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 23, 19, 38, 546450)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 23, 19, 38, 546450)
            ),
        ),
        migrations.AlterField(
            model_name="privacy_policy",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 23, 19, 38, 546450)
            ),
        ),
        migrations.AlterField(
            model_name="terms_conditions",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 23, 19, 38, 546450)
            ),
        ),
    ]
