# Generated by Django 4.2.7 on 2024-01-17 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exchange_rates",
            "0062_post_meta_description_alter_about_created_at_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.AlterField(
            model_name="about",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 41, 9, 596979)
            ),
        ),
        migrations.AlterField(
            model_name="fuel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 41, 9, 595980)
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 41, 9, 593980)
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 41, 9, 598980)
            ),
        ),
        migrations.AlterField(
            model_name="privacy_policy",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 41, 9, 597980)
            ),
        ),
        migrations.AlterField(
            model_name="terms_conditions",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 41, 9, 597980)
            ),
        ),
    ]
