# Generated by Django 4.2.7 on 2024-01-17 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exchange_rates",
            "0064_post_alter_about_created_at_alter_fuel_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 43, 5, 981685)
            ),
        ),
        migrations.AlterField(
            model_name="fuel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 43, 5, 979681)
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 43, 5, 977680)
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 43, 5, 983686)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 43, 5, 980686)
            ),
        ),
        migrations.AlterField(
            model_name="privacy_policy",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 43, 5, 982686)
            ),
        ),
        migrations.AlterField(
            model_name="terms_conditions",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 16, 43, 5, 981685)
            ),
        ),
    ]
