# Generated by Django 4.2.7 on 2024-01-17 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exchange_rates",
            "0065_alter_about_created_at_alter_fuel_created_at_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetaDetails",
        ),
        migrations.AlterField(
            model_name="about",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 19, 14, 802701)
            ),
        ),
        migrations.AlterField(
            model_name="fuel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 19, 14, 801703)
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 19, 14, 799701)
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 19, 14, 805707)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 19, 14, 802701)
            ),
        ),
        migrations.AlterField(
            model_name="privacy_policy",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 19, 14, 804700)
            ),
        ),
        migrations.AlterField(
            model_name="terms_conditions",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 19, 14, 803701)
            ),
        ),
    ]
