# Generated by Django 4.2.7 on 2024-01-17 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0066_delete_metadetails_alter_about_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.TextField()),
                ("index_ar", models.TextField()),
                ("currencies", models.TextField()),
                ("currencies_ar", models.TextField()),
                ("gold", models.TextField()),
                ("gold_ar", models.TextField()),
                ("fuel", models.TextField()),
                ("fuel_ar", models.TextField()),
                ("news_ar", models.TextField()),
            ],
            options={
                "verbose_name": "meta details",
                "verbose_name_plural": "meta details",
            },
        ),
        migrations.AlterField(
            model_name="about",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 23, 29, 96483)
            ),
        ),
        migrations.AlterField(
            model_name="fuel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 23, 29, 95484)
            ),
        ),
        migrations.AlterField(
            model_name="gold",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 23, 29, 93485)
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 23, 29, 98485)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 23, 29, 96483)
            ),
        ),
        migrations.AlterField(
            model_name="privacy_policy",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 23, 29, 98485)
            ),
        ),
        migrations.AlterField(
            model_name="terms_conditions",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 17, 18, 23, 29, 97484)
            ),
        ),
    ]
