# Generated by Django 4.2.7 on 2024-01-23 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0067_metadetails_alter_about_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 12, 58, 41, 940783)),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 12, 58, 41, 938228)),
        ),
        migrations.AlterField(
            model_name='gold',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 12, 58, 41, 937335)),
        ),
        migrations.AlterField(
            model_name='links',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 12, 58, 41, 942026)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 12, 58, 41, 940252)),
        ),
        migrations.AlterField(
            model_name='privacy_policy',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 12, 58, 41, 941592)),
        ),
        migrations.AlterField(
            model_name='terms_conditions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 12, 58, 41, 941254)),
        ),
    ]
